import type { TimelineEntry } from "./types";

/**
 * Chronological spine 2019–2026. Prefer cautious summaries.
 */
export const timeline: TimelineEntry[] = [
  {
    id: "2019-hsc",
    date: "2019",
    endDate: "2020",
    kind: "education",
    title: "Higher Secondary (PCM)",
    summary: "Mission English Higher Secondary School, Seoni.",
    relatedSlug: "mission-higher-secondary",
  },
  {
    id: "2020-btech-start",
    date: "2020-09",
    endDate: "2024-07",
    kind: "education",
    title: "B.Tech CSE — LNCTS Bhopal",
    summary: "Computer Science Engineering; graduated 2024.",
    relatedSlug: "lncts-btech-cse",
  },
  {
    id: "2020-gcp",
    date: "2020",
    kind: "recognition",
    title: "Google Cloud training path",
    summary: "30 Days of Google Cloud program (certificate on file).",
    relatedSlug: "google-cloud-30-days",
  },
  {
    id: "2021-iitm-bs",
    date: "2021",
    endDate: "2024",
    kind: "education",
    title: "BS Data Science — IIT Madras",
    summary: "Parallel degree in Data Science and Applications.",
    relatedSlug: "iitm-bs-data-science",
  },
  {
    id: "2021-aws-ml",
    date: "2021-04",
    kind: "recognition",
    title: "AWS Introduction to Machine Learning",
    summary: "Foundational ML course completion.",
    relatedSlug: "aws-intro-ml",
  },
  {
    id: "2022-mun",
    date: "2022-03",
    endDate: "2022-09",
    kind: "leadership",
    title: "MUN core organizing — LNCT",
    summary: "Conference operations and outreach.",
    relatedSlug: "mun-lnct",
  },
  {
    id: "2022-beyond-words",
    date: "2022-04",
    endDate: "2022-05",
    kind: "leadership",
    title: "Beyond The Words open mic — IITM",
    summary: "Event organization at IIT Madras.",
    relatedSlug: "beyond-the-words",
  },
  {
    id: "2022-uipath",
    date: "2022-07",
    endDate: "2023-07",
    kind: "role",
    title: "UiPath Student Developer Champion",
    summary: "Workshops, mentoring, and RPA community work.",
    relatedSlug: "uipath-champion",
  },
  {
    id: "2022-bachpan",
    date: "2022-06",
    endDate: "2023-01",
    kind: "leadership",
    title: "BachpanShala / We Care tutoring",
    summary: "Education support for children — grounded volunteering.",
    relatedSlug: "bachpanshala",
  },
  {
    id: "2022-salesforce",
    date: "2022-10",
    endDate: "2022-12",
    kind: "role",
    title: "Salesforce virtual internship",
    summary: "CRM / platform fundamentals and projects.",
    relatedSlug: "salesforce-virtual",
  },
  {
    id: "2022-kanha",
    date: "2022-09",
    endDate: "2023-07",
    kind: "role",
    title: "Kanha House WebOps — IITM",
    summary: "House website, content, and event tech support.",
    relatedSlug: "kanha-webops",
  },
  {
    id: "2023-iha",
    date: "2023-01",
    endDate: "2023-02",
    kind: "project",
    title: "Iha by Himani client site",
    summary: "Art studio marketing site shipped.",
    relatedSlug: "iha-by-himani",
  },
  {
    id: "2023-cisco",
    date: "2023-07",
    kind: "recognition",
    title: "Cisco CyberOps Associate",
    summary: "Networking Academy cybersecurity operations cert.",
    relatedSlug: "cisco-cyberops-associate",
  },
  {
    id: "2023-legal-nlp",
    date: "2023-08",
    endDate: "2023-12",
    kind: "project",
    title: "Legal NLP investigation",
    summary: "Exploratory NLP for contracts — not a publication.",
    relatedSlug: "legal-nlp-contracts",
  },
  {
    id: "2023-rasor",
    date: "2023-12",
    kind: "role",
    title: "Web Developer intern — RaSoR IITM",
    summary: "Research-adjacent web development.",
    relatedSlug: "rasor-iitm",
  },
  {
    id: "2024-focdot",
    date: "2024-04",
    endDate: "present",
    kind: "role",
    title: "SDE — AI Engineer at FoCDoT",
    summary: "RLHF-oriented evaluation and generative AI engineering.",
    relatedSlug: "focdot-sde-ai",
  },
  {
    id: "2024-products",
    date: "2024",
    endDate: "present",
    kind: "product",
    title: "Open Framework + AyushMushrooms MVPs",
    summary: "Civil society DPI concept and agrotech brand site.",
    relatedSlug: "the-open-framework",
  },
  {
    id: "2024-selected-projects",
    date: "2024",
    endDate: "present",
    kind: "project",
    title: "Shiksha-Mitra, Expert-O, Overlay Text Box",
    summary: "Education platform, studio site, and Chrome extension.",
  },
  {
    id: "2024-praful",
    date: "2024",
    kind: "project",
    title: "Praful H. professional site",
    summary: "Client portfolio for a UK-based technology leader.",
    relatedSlug: "praful-h",
  },
  {
    id: "2024-grad",
    date: "2024-07",
    kind: "education",
    title: "B.Tech graduation",
    summary: "Completed CSE at LNCTS Bhopal.",
    relatedSlug: "lncts-btech-cse",
  },
  {
    id: "2025-outlier",
    date: "2025-08",
    endDate: "present",
    kind: "role",
    title: "Generative AI Engineer — Outlier",
    summary: "Part-time LLM dataset and evaluation workflows.",
    relatedSlug: "outlier-genai",
  },
  {
    id: "2026-content-layer",
    date: "2026-08",
    kind: "life",
    title: "Structured content layer for digital home",
    summary:
      "Portfolio content moved into typed modules as a single source of truth.",
  },
];
